wiki.core doesn't have settings.py; In fact wiki.conf does
Addressing:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/neo/.virtualenvs/pp_new/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/Users/neo/.virtualenvs/pp_new/lib/python3.5/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/Users/neo/.virtualenvs/pp_new/lib/python3.5/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/neo/.virtualenvs/pp_new/lib/python3.5/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/Users/neo/.virtualenvs/pp_new/lib/python3.5/site-packages/django/apps/config.py", line 123, in create
    import_module(entry)
  File "/Users/neo/.virtualenvs/pp_new/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/Users/neo/GDrive/myCoding/barangaroo-digital-experience-partner-portal/website/barangaroo/plugins/wiki/search/__init__.py", line 2, in <module>
    from wiki.plugins.haystack.search_indexes import ArticleIndex
  File "/Users/neo/.virtualenvs/pp_new/lib/python3.5/site-packages/wiki/plugins/haystack/__init__.py", line 3, in <module>
    from wiki.core import settings
ImportError: cannot import name 'settings'

Process finished with exit code 1